{{- if .Values.java.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java
  labels:
    app: demo-java
    {{- include "coroot-demo-apps.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.java.replicaCount }}
  selector:
    matchLabels:
      app: demo-java
  template:
    metadata:
      labels:
        app: demo-java
      {{- with .Values.java.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: demo-java
          image: {{ include "coroot-demo-apps.image" (merge (dict "registry" $.Values.imageRegistry) .Values.java.image) | quote }}
          imagePullPolicy: {{ .Values.java.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.java.service.port }}
          env:
            {{- range $k, $v := .Values.java.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.java.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: demo-java
  labels:
    app: demo-java
    {{- include "coroot-demo-apps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.java.service.type }}
  selector:
    app: demo-java
  ports:
    - port: {{ .Values.java.service.port }}
      targetPort: {{ .Values.java.service.port }}
      name: http
{{- end }}
